---
- hosts: 192.168.56.3
  become: true 
  tasks:
   - name: Install Httpd Server 
     yum : name=httpd state=present 
   - name: restart service 
     service:
       name: httpd 
       state: started 
   - name: copy files from one location to another location 
     copy:
       src: index.html
       dest: /var/www/html/index.html
   - name: stop firewalld
     service:
       name: firewalld
       state: stopped
