---
- hosts: all
  become: true 
  tasks:
  - name: install apache http server on rhel
    yum:
      name: httpd 
      state: absent 
    when: ansible_os_family == "RedHat"
  - name: install apache http server on ubuntu
    apt:
      name: apache2
      state: absent 
    when: ansible_os_family == "Debian"
